DROP TABLE IF EXISTS Account;

CREATE TABLE Account (
  ID INT NOT NULL AUTO_INCREMENT,
  UserName VARCHAR2(255) NOT NULL DEFAULT '',
  Email VARCHAR2(255) NOT NULL DEFAULT '',
  Address VARCHAR2(255) NOT NULL DEFAULT '',
  PhoneNum VARCHAR2(20) NOT NULL DEFAULT '',
  Balance INT NOT NULL DEFAULT 0,
  TripStatus BIT,
  Permissions BIT,
  AccountNum INT NOT NULL,
  PRIMARY KEY (ID));